# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssh-matrix" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "a568a267fa4e1f7164aaf73a5a16a5e967c364d3c8554eefe522ff6f3f18777f"
      url "https://github.com/umit144/ssh-matrix/releases/download/v#{version}/ssh-matrix-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "2d7aca4af14f387d4e8a078e18e6f1efc386f51f2d7c5578e50d02d7415c9702"
      url "https://github.com/umit144/ssh-matrix/releases/download/v#{version}/ssh-matrix-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0ec1366b283d3f6361e1d23fe58d36e17e33c37df03eb8d4e404eb6013dd2636"
      url "https://github.com/umit144/ssh-matrix/releases/download/v#{version}/ssh-matrix-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "a9ff58f800a812c4af0b4b336111798c4c772f118a1ab22fbdeab0ff6fe4ac35"
      url "https://github.com/umit144/ssh-matrix/releases/download/v#{version}/ssh-matrix-linux-arm64.tar.gz"
    end
  end

  name "ssh-matrix"
  desc "A terminal UI for browsing and connecting to SSH hosts"
  homepage "https://github.com/umit144/ssh-matrix"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssh-matrix"

  # No zap stanza required

end
