# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssh-matrix" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "136349f4c61e6a137276868497a666cc66602b2b6637eedaa2c9086bf2466ccb"
      url "https://github.com/umit144/ssh-matrix/releases/download/v#{version}/ssh-matrix-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "3561f1a8fbb0a0e661f7213aa1a35ab2be838754ae0ba91b3a67e68eaaaf2f3b"
      url "https://github.com/umit144/ssh-matrix/releases/download/v#{version}/ssh-matrix-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "372020d5262a9f42fd1bab6f18d54fce7a6e5cd54355e598177a14f553dcc88b"
      url "https://github.com/umit144/ssh-matrix/releases/download/v#{version}/ssh-matrix-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "b21fb14616fea95d01f98559fe9fe4e8f835316a68b9b19a392c7bd3cb36f9d8"
      url "https://github.com/umit144/ssh-matrix/releases/download/v#{version}/ssh-matrix-linux-arm64.tar.gz"
    end
  end

  name "ssh-matrix"
  desc "A terminal UI for browsing and connecting to SSH hosts"
  homepage "https://github.com/umit144/ssh-matrix"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssh-matrix"

  # No zap stanza required

end
