# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssh-matrix" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "bd50025ca8930102757cc59d3e02b43fe247f0ff95d4a46180b8a8cb7d21699b"
      url "https://github.com/umit144/ssh-matrix/releases/download/v#{version}/ssh-matrix-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "4f5b491be1a7c5ffccb986251771f8da30e2a93596a2a45b80365a215d3317bb"
      url "https://github.com/umit144/ssh-matrix/releases/download/v#{version}/ssh-matrix-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "514628948ca52a804768c9d13f342547dfa63c890abaab59ec6c05060fe42ca2"
      url "https://github.com/umit144/ssh-matrix/releases/download/v#{version}/ssh-matrix-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "7ebbf30e2952a849fd3ade1333738e7537554d2140a8ed900eaf3944463dc086"
      url "https://github.com/umit144/ssh-matrix/releases/download/v#{version}/ssh-matrix-linux-arm64.tar.gz"
    end
  end

  name "ssh-matrix"
  desc "A terminal UI for browsing and connecting to SSH hosts"
  homepage "https://github.com/umit144/ssh-matrix"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssh-matrix"

  # No zap stanza required

end
